### ISSUE TITLE
一直在洗牌中... 

### ISSUE THREAD

**Issue by chilohwei** [circle-hotaru/tarot-master#1]
测试了本地运行，以及提供的demo，一直提示在洗牌中...  作者能帮忙看下怎么解决吗？

**Comment by circle-hotaru** [comment]
感谢使用，已经修复了。
fix: https://github.com/circle-hotaru/tarot-master/commit/0d93789d02bcf9122cc8ddac21422d731030c428

**Comment by chilohwei** [comment]
感谢，已经可以使用了
